"""added in_opponent bool to playbyplay

Revision ID: 33e618101fb0
Revises: c5c266085d2e
Create Date: 2025-08-09 15:26:35.716000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e618101fb0'
down_revision: Union[str, Sequence[str], None] = 'c5c266085d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play_by_play', sa.Column('is_opponent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('play_by_play', 'is_opponent')
    # ### end Alembic commands ###
