"""removed starter column

Revision ID: 8a8023f0799a
Revises: c73239d4dddb
Create Date: 2025-08-15 10:48:00.868827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8023f0799a'
down_revision: Union[str, Sequence[str], None] = 'c73239d4dddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_participants', 'starter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_participants', sa.Column('starter', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
