"""undone recent revision

Revision ID: a0d931e437a8
Revises: 679950bcb572
Create Date: 2025-08-06 16:34:57.708505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d931e437a8'
down_revision: Union[str, Sequence[str], None] = '679950bcb572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('comments_team_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.drop_column('comments', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_team_id_fkey'), 'comments', 'users', ['team_id'], ['id'])
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
