"""removed video_url

Revision ID: a5a515880792
Revises: 33e618101fb0
Create Date: 2025-08-13 09:51:48.821485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a515880792'
down_revision: Union[str, Sequence[str], None] = '33e618101fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
