"""substitution table

Revision ID: c73239d4dddb
Revises: 23711a17c5cc
Create Date: 2025-08-15 10:40:08.814063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73239d4dddb'
down_revision: Union[str, Sequence[str], None] = '23711a17c5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('substitutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('timestamp_seconds', sa.Integer(), nullable=False),
    sa.Column('on_court', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_substitutions_game_id'), 'substitutions', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_substitutions_game_id'), table_name='substitutions')
    op.drop_table('substitutions')
    # ### end Alembic commands ###
