"""play-by-play added index

Revision ID: d72e27949626
Revises: a0d931e437a8
Create Date: 2025-08-06 16:53:21.009548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72e27949626'
down_revision: Union[str, Sequence[str], None] = 'a0d931e437a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_play_by_play_game_id'), 'play_by_play', ['game_id'], unique=False)
    op.create_index('ix_play_by_play_game_time', 'play_by_play', ['game_id', 'timestamp_seconds'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_play_by_play_game_time', table_name='play_by_play')
    op.drop_index(op.f('ix_play_by_play_game_id'), table_name='play_by_play')
    # ### end Alembic commands ###
